server:
  port: 9001
spring:
  application:
    name: activemq-production
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qqq?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456


  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    packages:
      trust-all: true
  jms:
    # 指定发送的模式 ，true为pubsub false为点对点;
    pub-sub-domain: false
    template:
      delivery-mode: persistent