server:
  port: 9000

spring:
  application:
    name: active-producer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.115.55.168:3306/qqqcode?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  artemis:
    mode: native
    host: 47.115.55.168 # artermis连接地址
    port: 61616 # artermis连接端口
    user: admin # 用户名
    password: admin # 密码
#    send-timeout: # 发送超时时间
    pool:
      enabled: false # 是否创建 JmsPoolConnectionFactory 连接池
      idle-timeout: 30s # 空闲连接超时时间
      max-connections: 50 # 连接池中最大连接数
      max-sessions-per-connection: 100 # 每个连接最大会话

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


mqcofig:
  asyqueue: QqqAsyQueue